name: 'conectar-user-management'

services:
  postgresql:
    image: 'bitnami/postgresql:17.5.0'
    container_name: 'db'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=user_management
    ports:
      - '5432:5432'
    volumes:
      - './postgresql_data:/bitnami/postgresql'
    
